name: Dart

on:
  pull_request:
    branches:
      - main
      - develop
      - features/**
      - hotfix/**
    # paths:
    #   - '**/*.dart'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.12.0

      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze
